TODO
// update card to use manacost, typeline, oracletext, power, toughness

login auth


fix deck handling (structure and execution)


AI bot
real-time updates (signalR)
###
GET http://localhost:5189/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoidXNlciIsImV4cCI6MTc3MjkzMTI2MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.pHujy090vNWIropyynTt6MYBLK338WMy3jkPEfBoL3M
###
POST http://localhost:5189/auth/register
Content-Type: application/json

{
    "email": "user@email.com",
    "username": "user",
    "password": "password"
}
###
POST http://localhost:5189/auth/login
Content-Type: application/json

{
    "email": "user@email.com",
    "password": "password"
}
###
GET http://localhost:5189/debug/pack/
### get the draft sessions
GET http://localhost:5189/DraftSession/
### get the players view
GET http://localhost:5189/DraftSession/1/Player/1
### get the players
GET http://localhost:5189/Players/
### create a player
POST http://localhost:5189/Players/
Content-Type: application/json

{
    "name": "User",
    "IsBot": false,
    "Decks": []
}
### create a draft session
POST http://localhost:5189/DraftSession/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoidXNlciIsImV4cCI6MTc3MjkzMTI2MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.pHujy090vNWIropyynTt6MYBLK338WMy3jkPEfBoL3M
Content-Type: application/json

{
    "setCode": "ECL",
    "playerCount": 8,
    "createdAt": "2026-02-19T00:00:00Z"
}
###
POST http://localhost:5189/DraftSession/3/Join/8
### start the session
POST http://localhost:5189/DraftSession/3/Start
### pick a card
POST http://localhost:5189/DraftSession/3/Pick
Content-Type: application/json

{
    "playerId": 1,
    "packCardId": 768
}

### advance the gamestate
POST http://localhost:5189/DraftSession/3/Advance
### make the decks at end
POST http://localhost:5189/DraftSession/1/CreateDecks
### clear all players in session
POST http://localhost:5189/DraftSession/1/Clear
###
DELETE http://localhost:5189/DraftSession/2