TODO
implement routes for creating, managing, and deleting players and decks.

start on the draft game loop
- status and player count in draftsession
- join route for players to join a draft session
- start route to start the draft session (move pack generation to here)
- modify get draftsession route to include players and status

###
GET http://localhost:5189/DraftSession/2
###
GET http://localhost:5189/Players/
###
POST http://localhost:5189/Players/
Content-Type: application/json

{
    "name": "Player1",
    "IsBot": false,
    "Decks": []
}
###
POST http://localhost:5189/DraftSession/
Content-Type: application/json

{
    "setCode": "ECL",
    "playerCount": 8,
    "createdAt": "2026-02-19T00:00:00Z"
}
###
GET http://localhost:5189/DraftSession/1
###
DELETE http://localhost:5189/DraftSession/1
###
POST http://localhost:5189/DraftSession/2/Join/3
###
PATCH http://localhost:5189/DraftSession/2
Content-Type: application/json

{
    "DraftState": "InProgress"
}
###
GET http://localhost:5189/Players/1
###
DELETE http://localhost:5189/Players/1
###
GET http://localhost:5189/Players/1/Decks/
###
GET http://localhost:5189/Players/1/Decks/1
###
POST http://localhost:5189/Players/1/Decks
Content-Type: application/json

{
    "name": "Draft Deck 3",
    "cards": [
        {
            "cardId": 243,
            "isSideboard": false
        },
        {
            "cardId": 144,
            "isSideboard": false
        }
    ]
}
###
GET http://localhost:5189/Players/1/Decks/4
###
DELETE http://localhost:5189/Players/1/Decks/2
###
GET http://localhost:5189/Packs/1
###
GET http://localhost:5189/Packs/1/1
###
POST http://localhost:5189/Packs/1/1
Content-Type: application/json

{
    "IsPicked": true,
    "PickedByPlayerId": 1
}
###