TODO
improve pack generation
login auth
AI bot
real-time updates (signalR)



### get the draft sessions
GET http://localhost:5189/DraftSession/2
### get the players view
GET http://localhost:5189/DraftSession/2/Player/9
### get the players
GET http://localhost:5189/Players/
### create a player
POST http://localhost:5189/Players/
Content-Type: application/json

{
    "name": "Player",
    "IsBot": false,
    "Decks": []
}
### create a draft session
POST http://localhost:5189/DraftSession/
Content-Type: application/json

{
    "setCode": "ECL",
    "playerCount": 8,
    "createdAt": "2026-02-19T00:00:00Z"
}
### join the session
POST http://localhost:5189/DraftSession/2/Join/9
### start the session
POST http://localhost:5189/DraftSession/2/Start
### pick a card
POST http://localhost:5189/DraftSession/2/Pick
Content-Type: application/json

{
    "playerId": 9,
    "packCardId": 559
}

### advance the gamestate
POST http://localhost:5189/DraftSession/2/Advance
### make the decks at end
POST http://localhost:5189/DraftSession/1/CreateDecks
### clear all players in session
POST http://localhost:5189/DraftSession/1/Clear