// TODO //
make sure only the authorised user can access certain routes

frontend


reorganised the project backend to be sorted by feature rather than technical purpose
each feature contains its own breakdown of files by technical purpose


// ISSUES //
the pickdeadline is never updated in the database
treatments are never filled in PackCard
the player view endpoint can be used to see any players view point (change to remove playerId and instead use ClaimsPrinciple)

// maybe look at this
generalise the pack generation to work with other sets
GenerateSingleECLPack or GenerateSingleEOEPack or GenerateSingleMOMPack

contains
generateCommons(Set set, int amount)
generateUncommons(Set set, int amount, int specialprintWeighting)
generateWildcard(Set set, Chances cardChances) - Chances has weighings for C U R M cards
this will make it more scalable when implementing other sets

packs will generally contain 
6 commons
have a chance for a special guest in the 7th common slot
3 uncommons with a chance for a special printing
a wildcard with varied rarity weighting
rare / mythic with special printing
trad foil of any rarity
a land card


// AUTH ROUTES
### REGISTER USER [Y]
POST http://localhost:5189/api/auth/register
Content-Type: application/json

{
    "email": "nick@email.com",
    "username": "nick",
    "password": "password"
}
### GET USER DETAILS [Y]
GET http://localhost:5189/api/auth/1
### UPDATE USER DETAILS - role left null [Y]
PATCH http://localhost:5189/api/auth/1
Content-Type: application/json

{
    "email": "nick@email.com",
    "username": "jack"
}
### DELETE USER [Y]
DELETE http://localhost:5189/api/auth/1
### LOGIN [Y]
POST http://localhost:5189/api/auth/login 
Content-Type: application/json

{
    "email": "nick@email.com",
    "password": "password"
}

###
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoiamFjayIsImV4cCI6MTc3MzY5NzUxNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.gHYZOo2YadWmlLyFJ0e8L0dXrf6Snmuw0uu9XzUxlpo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoibmljayIsImV4cCI6MTc3MzY5ODY3OSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.XarltwWUSZu8EmzYCo6OW-xQTpJVtjY3gc112-faxOI


// DRAFT ROUTES
### CREATE A DRAFT SESSION [Y]
POST http://localhost:5189/api/DraftSession/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoiamFjayIsImV4cCI6MTc3MzY5NzUxNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.gHYZOo2YadWmlLyFJ0e8L0dXrf6Snmuw0uu9XzUxlpo
Content-Type: application/json

{
    "SetCode": "ECL",
    "playerCount": 8
}
### DELETE A DRAFT SESSION [Y]
DELETE http://localhost:5189/api/DraftSession/1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoiamFjayIsImV4cCI6MTc3MzY5NDI1NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.mE9Qo0Yemv4ag3jSnE29k4HpaPkUeoTZO9POCWTDTiQ
### JOIN A DRAFT SESSION [Y]
POST http://localhost:5189/api/DraftSession/2/Join/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoiamFjayIsImV4cCI6MTc3MzY5NzUxNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.gHYZOo2YadWmlLyFJ0e8L0dXrf6Snmuw0uu9XzUxlpo
### START A DRAFT SESSION [Y]
POST http://localhost:5189/api/DraftSession/1/Start
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoiamFjayIsImV4cCI6MTc3MzY5NDI1NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.mE9Qo0Yemv4ag3jSnE29k4HpaPkUeoTZO9POCWTDTiQ
### GET ALL DRAFT SESSIONS [Y]
GET http://localhost:5189/api/DraftSession/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoiamFjayIsImV4cCI6MTc3MzY5NjM3NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.2nXmt7Aj43HL6aYgQu5jP7x5Sahx57XgvmKZsOjDDVg
### GET DETAILS OF A SPECIFIC DRAFT [Y]
GET http://localhost:5189/api/DraftSession/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoiamFjayIsImV4cCI6MTc3MzY5NjM3NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.2nXmt7Aj43HL6aYgQu5jP7x5Sahx57XgvmKZsOjDDVg
### GET A SPECIFIC PLAYERS VIEW OF THE DRAFT [Y]
GET http://localhost:5189/api/DraftSession/1/self
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVzZXJuYW1lIjoibmljayIsImV4cCI6MTc3MzY5ODY3OSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTg5LyJ9.XarltwWUSZu8EmzYCo6OW-xQTpJVtjY3gc112-faxOI
###


// DECK ROUTES
### GET PLAYER DECK
GET http://localhost:5189/api/Users/1/Players/1/Decks
###